const resList = [
    {
      info: {
        id: "629679",
        name: "La Pino'z Pizza",
        cloudinaryImageId: "n8z10pn06a4ks3ej5das",
        locality: "Sector 2",
        areaName: "G B Nagar",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        avgRating: 3.8,
        parentId: "4961",
        avgRatingString: "3.8",
        totalRatingsString: "1K+",
      },
    },
    {
      info: {
        id: "562781",
        name: "The Burger Club",
        cloudinaryImageId: "h4ppdoav5fdi0gsswpab",
        locality: "Ch Nitin Khari Marg",
        areaName: "Sector 141",
        costForTwo: "₹250 for two",
        cuisines: ["American", "Desserts", "Beverages"],
        avgRating: 4.1,
        parentId: "2285",
        avgRatingString: "4.1",
        totalRatingsString: "1K+",
      },
    },
    {
      info: {
        id: "511804",
        name: "Taza Day",
        cloudinaryImageId: "lfdearoe1khcfds1yvta",
        locality: "Knowledge Park",
        areaName: "Greater Noida",
        costForTwo: "₹300 for two",
        cuisines: ["Indian"],
        avgRating: 3.1,
        parentId: "306145",
        avgRatingString: "3.1",
        totalRatingsString: "10+",
      },
    },
    {
      info: {
        id: "37553",
        name: "Night Food Express",
        cloudinaryImageId: "mkpuwhtxeapb9zhhfq6d",
        locality: "Alpha 1",
        areaName: "Greater Noida",
        costForTwo: "₹350 for two",
        cuisines: ["Indian", "Chinese", "Continental"],
        avgRating: 3.8,
        parentId: "148742",
        avgRatingString: "3.8",
        totalRatingsString: "5K+",
      },
    },
    {
      info: {
        id: "622623",
        name: "Smoke House Burger",
        cloudinaryImageId: "p0wdirx7ghmxi6tx6dhi",
        locality: "Knowledge Park",
        areaName: "Greater Noida",
        costForTwo: "₹300 for two",
        cuisines: ["Burgers", "Snacks", "Italian"],
        avgRating: 4,
        parentId: "370551",
        avgRatingString: "4.0",
        totalRatingsString: "500+",
      },
    },
    {
      info: {
        id: "248755",
        name: "Hashtag Foods",
        cloudinaryImageId: "q8elznxehj5bz4ybambc",
        locality: "Alpha 2",
        areaName: "Greater Noida",
        costForTwo: "₹250 for two",
        cuisines: ["Street Food", "Italian", "American", "Desserts", "Beverages"],
        avgRating: 4.1,
        parentId: "10519",
        avgRatingString: "4.1",
        totalRatingsString: "500+",
      },
    },
    {
      info: {
        id: "587701",
        name: "Keventers Ice Cream",
        cloudinaryImageId: "763214ca062fe36dfb5ef23c57856126",
        locality: "Alpha 2",
        areaName: "Greater Noida",
        costForTwo: "₹200 for two",
        cuisines: ["Ice Cream", "Desserts"],
        avgRating: 4.3,
        veg: true,
        parentId: "272044",
        avgRatingString: "4.3",
        totalRatingsString: "100+",
      },
    },
    {
      info: {
        id: "385145",
        name: "Momo Shomo",
        cloudinaryImageId: "nwow7xpgtgfu2a4nuqwq",
        locality: "Alpha 1",
        areaName: "Greater Noida",
        costForTwo: "₹300 for two",
        cuisines: [
          "Chinese",
          "Street Food",
          "Tibetan",
          "Asian",
          "Indian",
          "North Eastern",
          "Beverages",
        ],
        avgRating: 4.3,
        parentId: "21859",
        avgRatingString: "4.3",
        totalRatingsString: "1K+",
      },
    },
    {
      info: {
        id: "430244",
        name: "The Waffle Co.",
        cloudinaryImageId: "4866e080f03ed46d77faa197b224deba",
        locality: "Alpha 1",
        areaName: "Alpha 1",
        costForTwo: "₹200 for two",
        cuisines: ["Desserts", "Waffle", "Beverages"],
        avgRating: 4.4,
        parentId: "5143",
        avgRatingString: "4.4",
        totalRatingsString: "1K+",
      },
    },
    {
      info: {
        id: "511884",
        name: "Taza Day",
        cloudinaryImageId: "lfdearoe1khcfds1yvta",
        locality: "Knowledge Park",
        areaName: "Greater Noida",
        costForTwo: "₹300 for two",
        cuisines: ["Indian"],
        avgRating: 3.1,
        parentId: "306145",
        avgRatingString: "3.1",
        totalRatingsString: "10+",
      },
    },
  ];
  
  export default resList;